---
# This pipeline is run for EVERY branch
kind: pipeline
name: default
steps:
  - name: git-tag
    image: docker:git
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - git remote set-url origin https://${GITHUB_TOKEN}@github.com/HelloWorld-09/testrep.git
      - git tag v1.1
      - git push origin v1.1