---
kind: pipeline
name: default_1
steps:
- name: test
  image: alpine
  environment:
    SSH_KEY:
      from_secret: private_ssh_key
  commands:
    - ls -a
    - apk add openssh
    - apk add git
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p /.ssh && touch /.ssh/known_hosts
    - ssh-keyscan -t rsa github.com >> /.ssh/known_hosts
    - chmod 644 /.ssh/known_hosts
    - git config --global user.email $DRONE_COMMIT_AUTHOR_EMAIL
    - git config --global user.name $DRONE_COMMIT_AUTHOR_NAME
    - git config --global --add url."git@github.com:".insteadOf "https://github.com/"
    - git fetch --all
    - git checkout -b feature
    - touch test.txt
    - git add .
    - git commit -m "Test feature"
    - git push origin feature
