---
kind: pipeline
name: default_1
steps:
- name: test
  image: alpine
  environment:
    SSH_KEY:
      from_secret: private_ssh_key
  commands:
    - apk add openssh
    - mkdir /.ssh
    - echo $SSH_KEY > /.ssh/id_rsa
    - chmod 400 /.ssh/id_rsa
    - ssh-add /.ssh/id_rsa
