---
kind: pipeline
name: default_1
steps:
- name: test
  image: alpine
  commands:
    - mkdir /testdir
- name: push commit
  image: appleboy/drone-git-push
  settings:
    ssh_key:
      from_secret: private_ssh_key
    remote_name: git@github.com:HelloWorld-09/testrep.git
    branch: feature
    path: /drone