---
kind: pipeline
name: default_1
steps:
- name: test
  image: alpine
  commands:
    - apk add --update py-pip
    - apk add git
    - pip install cookiecutter
    - pip install click==7.1.2
    - cookiecutter --no-input https://github.com/HelloWorld-09/testrep.git owner_email="test" co_owner_email="test1"
- name: push commit
  image: appleboy/drone-git-push
  settings:
    ssh_key: 
      from_secret: private_ssh_key
    remote_name: git@github.com:HelloWorld-09/testrep.git
    branch: feature
    path: testrepcc/