---
kind: pipeline
name: default_1
steps:
- name: test
  image: alpine
  environment:
    SSH_KEY:
      from_secret: private_ssh_key
  commands:
    - ls -a
    - apk add openssh
    - apk add git
    - eval $(ssh-agent -s)
    - mkdir /.ssh
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - git config --global user.email $DRONE_COMMIT_AUTHOR_EMAIL
    - git config --global user.name $DRONE_COMMIT_AUTHOR_NAME
    - git branch feature
    - git switch feature
    - git add .
    - git commit -m "Test feature"
    - git push origin feature
