---
kind: pipeline
name: default_1
steps:
- name: test
  image: alpine
  commands:
    - mkdir /testdir
    - touch /testdir/test.txt
- name: push commit
  image: appleboy/drone-git-push
  settings:
    ssh_key:
      from_secret: private_ssh_key
    remote_name: origin
    branch: feature
    path: /testdir
