---
kind: pipeline
name: default_1
steps:
- name: test
  image: alpine
  environment:
    SSH_KEY:
      from_secret: private_ssh_key
  commands:
    - apk add openssh
    - eval $(ssh-agent -s)
    - mkdir /.ssh
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - chmod 400 /.ssh/id_rsa
    - ssh-add /.ssh/id_rsa
